[package]
name = "solid_arx"
version = "0.1.0"
edition = "2021"

[lib]
name = "solid_arx_lib"
path = "src/lib.rs"  # Path relativo per la libreria

# Definizione del binario per il CLI 
[[bin]] 
name = "arx" 
path = "src/main.rs"  # Path del CLI

# Feature Flags
[features]
# Definizione delle feature per i moduli
auth = []
crud = []
api = []
file_management = []
task_automation = []
blockchain = []
ml = []
frontend = []  # Da abilitare solo se si implementa un modulo Rust per frontend

# Definizione delle feature per i diversi tipi di applicazioni
webapp = ["auth", "crud", "api", "frontend"]
api_backend = ["auth", "crud", "api"]
desktop = ["auth", "crud", "file_management", "frontend"]
automation = ["task_automation"]
embedded = []  # I sistemi embedded utilizzano solo core e monitoring

# Dipendenze comuni a tutti i moduli
[dependencies]
fern = "0.7.0"  # Per la fernanda
chrono = "0.4.19"  # Per la gestione del tempo
colored = "2.0"  # Per colorare i messaggi di log
clap = { version = "4.5.20", features = ["derive"] }  # Per il parsing del CLI
once_cell = "1.17.1"  # Per la gestione di valori statici
lazy_static = "1.4"  # Per la gestione di valori statici
log = "0.4.22" 
diesel = { version = "2.2.4", features = ["postgres", "r2d2", "chrono"] }
dotenvy = "0.15"  # Per gestire le variabili di ambiente
cfg-if = "1.0.0"  # Per definire condizioni di compilazione
mongodb = "3.1.0" # Per la connessione a MongoDB